### PR TITLE
Makefile: Add `stylish` target

### PR DESCRIPTION
**Pull request by ttuegel**
The `stylish` target runs `stylish-haskell` on every Haskell source file in the
repository. The `check` target now uses the `stylish` target in its
style-conformance test. The `check` target now suggests solutions to the errors
it detects.

###### Reviewer checklist

- [ ] Test coverage: `stack test --coverage`
- [ ] Public API documentation: `stack haddock`
- [ ] Style conformance: `stylish-haskell`

---

### CODE REVIEW

**Comment by ttuegel** [comment]
@traiansf An integration test is failing on Jenkins in a way that I can't reproduce on my machine:
```
/var/lib/jenkins/jobs/kore-pull-request/workspace/.build/k/k-distribution/target/release/k/bin/krun --haskell-backend-command "/var/lib/jenkins/jobs/kore-pull-request/workspace/.stack-work/install/x86_64-linux/lts-12.9/8.4.3/bin/kore-exec " tests/sum.imp --output-file tests/sum.output
Reading the input file TimeSpec {sec = 0, nsec = 46126}
Parsing the file TimeSpec {sec = 1, nsec = 911335381}
Verifying the definition TimeSpec {sec = 0, nsec = 77356956}
kore-exec: Error in module 'IMP' -> symbol 'Lbl'Stop'List' declaration (/var/lib/jenkins/jobs/kore-pull-request/workspace/src/main/k/working/imp-monosorted/imp-kompiled/definition.kore 204:10): Unexpected 'hook' attribute
CallStack (from HasCallStack):
  error, called at app/exec/Main.hs:382:33 in main:Main
diff -u tests/sum.output.golden tests/sum.output
--- tests/sum.output.golden	2018-10-15 08:54:16.102085521 -0500
+++ tests/sum.output	2018-10-15 09:06:43.310076986 -0500
@@ -1,13 +1,3 @@
-<generatedTop>
-  <T>
-    <k>
-      .
-    </k>
-    <state>
-      n |-> 0 sum |-> 15 .State
-    </state>
-  </T>
-  <generatedCounter>
-    0
-  </generatedCounter>
-</generatedTop>
+initTCell ( $IO |-> "on"
+$PGM |-> int n , sum , .Ids ; n = AInt 5 ; sum = AInt 0 ; while ( ! AId n <= AInt 0 ) { sum = AId sum + AId n ; n = AId n + - 1 ; }
+$STDIN |-> "" )
Makefile:20: recipe for target 'tests/sum.test' failed
make[2]: *** [tests/sum.test] Error 1
```

**Comment by traiansf** [comment]
Would it be possible that it got a different version of K?  Do we do a `make distclean`  ?

**Comment by ttuegel** [comment]
Jenkins does not do a `make distclean`, but from the log I can tell it is building K from the submodule, so I'm not sure that `distclean` would help.

**Comment by traiansf** [comment]
I was wondering whether it would be possible for Jenkins to see a leftover K submodule from a previous PR build and use that.  If so, then it could be using a different commit, if that PR updated the submodule, e.g.

**Comment by ttuegel** [comment]
So, the submodule wasn't left over, but some of the build products were. Still, it was rebuilding K each time, so I don't know what the problem was.

**Pull request merged**
