### PR TITLE
Remove single-quote delimiters from validation error messages

### LINKED ISSUE #2300: Do not put quotes around identifiers in error messages
Error messages (particularly from the validator) should not put quotes around Kore identifiers because this symbol is valid in identifiers! Spaces around identifiers is enough to set them apart.

We should audit the code in `Kore.ASTVerifier` for uses of `koreFail` (and related functions like `koreFailWithLocations`) that put quotes around identifiers.

### PR DESCRIPTION
**Pull request by emarzion**
Fixes #2300 

---

###### Review checklist

The author performs the actions on the checklist. The reviewer evaluates the work and checks the boxes as they are completed.

-   [ ] **Summary.** Write a summary of the changes. Explain what you did to fix the issue, and why you did it. Present the changes in a logical order. Instead of writing a summary in the pull request, you may push a clean Git history.
-   [ ] **Documentation.** Write documentation for new functions. Update documentation for functions that changed, or complete documentation where it is missing.
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the changes. Include any examples from the reported issue as integration tests.
-   [ ] **Clean up.** The changes are already clean. Clean up anything near the changes that you noticed while working. This does not mean only spatially near the changes, but logically near: any code that interacts with the changes!

### CODE REVIEW

**Review by andreiburdusa — COMMENTED** [review]
Should `squotes` also be removed [here](https://github.com/kframework/kore/blob/3628a3cb028c2824d19ae8748c8d032bc9b18cd3/kore/src/Kore/ASTVerifier/PatternVerifier/PatternVerifier.hs#L210) or [here](https://github.com/kframework/kore/blob/master/kore/src/Kore/IndexedModule/Resolvers.hs#L294)?

**Comment by MirceaS** [comment]
Don't we want to replace the single quotes with some other type of quote that is illegal inside an Id, such as ` or " ?

**Review by andreiburdusa — COMMENTED** [review]
I noticed [this `Text`](https://github.com/kframework/kore/blob/4ba7ffca3706ba0f1d1a8eda9a5df729c986cffe/kore/src/Kore/ASTVerifier/Error.hs#L70) that is given as an argument to [`koreFailWithLocationsWhen`]( https://github.com/kframework/kore/blob/5b29c15315753aa84a064fa391b63ec2d3cdb31f/kore/src/Kore/ASTVerifier/PatternVerifier.hs#L498). Maybe the single-quotes it contains should also be removed?

**Comment by ttuegel** [comment]
It looks like the test golden files need to be updated.

**Review by ttuegel — APPROVED** [review]

**Pull request merged**
