### PR TITLE
Experiment using logict-sequence

### PR DESCRIPTION
**Pull request by treeowl**
`msplit` for `LogicT` is expensive. This experiment swaps in `SeqT` instead to see if that helps or hurts matters.

Fixes #nnnn

### Estimate:

---

###### Review checklist

The author performs the actions on the checklist. The reviewer evaluates the work and checks the boxes as they are completed.

-   [ ] **Summary.** Write a summary of the changes. Explain what you did to fix the issue, and why you did it. Present the changes in a logical order. Instead of writing a summary in the pull request, you may push a clean Git history.
-   [ ] **Documentation.** Write documentation for new functions. Update documentation for functions that changed, or complete documentation where it is missing.
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the changes. Include any examples from the reported issue as integration tests.
-   [ ] **Clean up.** The changes are already clean. Clean up anything near the changes that you noticed while working. This does not mean only spatially near the changes, but logically near: any code that interacts with the changes!

### CODE REVIEW

**Comment by goodlyrottenapple** [comment]
The isse had to do with updating the `haskell.nix` dependency to the latest version, as they take a static snapshot of hackage every day and the version we were locked to obviously didn't have the latest hackage snapshot. For future reference, you will need to run:

```bash
nix flake lock --update-input haskell-nix
```
and
```
niv update haskell.nix
```
the niv one is being phased out, but still isn't entirely gone unfortunately.

**Comment by treeowl** [comment]
@goodlyrottenapple Why did you switch GHC versions? That seems to make it impossible to build due to version constraints in dependencies.

**Comment by goodlyrottenapple** [comment]
ah shoot, I switched versions because the latest haskell.nix binary caches seem to have dropped ghc 9.2.3 which meant the nix job started to compile GHC on my machine

**Comment by treeowl** [comment]
So ... do we need that newer cache, or has/will the old one update with more things from Hackage today?

**Comment by goodlyrottenapple** [comment]
no, I think they are on a rolling basis and newest builds only cache ghc 9.2.4/9.2.5... however the issue seems to be unrelated to the ghc version, namely happy 1.21 is broken/deprecated on hackage and the maintainers set `<0` base dependency, thus making it uninstallable... what i don't understand is why nix/cabal thinks we require specifically `1.21` when building the shell

**Comment by goodlyrottenapple** [comment]
given we want to investigate the impact of this change quickly, I would suggest going back to the old version of haskell.nix and specifying the library in `stack.yaml` via git:

```yaml
  - git: https://github.com/dagit/logict-sequence
    commit: 8a146299ff339733501950600fae1018a7acfe78
```

**Comment by treeowl** [comment]
Great idea! I'll do that once I've had my coffee.

**Comment by treeowl** [comment]
I'm not sure why the tests didn't start up last time; I rebased (there were some merge conflicts) and pushed again.

**Comment by treeowl** [comment]
Tests recently failed when something was looking for a `master` branch of `logict-sequence`. I don't know *why* it was doing such a thing, but no branch by that name exists. `logict-sequence` has a `main` branch instead. I cleaned things out again and ... we'll see.

**Comment by treeowl** [comment]
This seems related: https://github.com/NixOS/nix/pull/4638

I guess I can create a temporary `master` branch to help the script along, or something.

**Comment by treeowl** [comment]
I don't understand the integration test failure. Is a golden test file somehow missing?

**Comment by jberthold** [comment]
> I don't understand the integration test failure. Is a golden test file somehow missing?

[Line 8784 says `Killed`](https://github.com/runtimeverification/haskell-backend/actions/runs/3539477037/jobs/5971066327#step:5:8784), I guess that's why it is failing. Why it got killed? No idea.

**Comment by treeowl** [comment]
> The best option would probably be to run these tests locally and watch the resources. It may well be that there is a memory leak or something.

Yeah, my strong bet is that we're retaining things that would be cheaper to recalculate instead. For example, if we use both `m <|> a` and `m <|> b`, then we'll fully realize `m`, when we may actually want to just build and consume it lazily twice. `LogicT` will be less susceptible to that issue because it deals with functions, which GHC tends not to think of as "data" by default. Fixing that kind of problem often requires substantial changes, so I'll focus on the unifier replacement for right now.

**Comment by treeowl** [comment]
[whoops.tar.gz](https://github.com/runtimeverification/haskell-backend/files/10108765/whoops.tar.gz)

**Comment by treeowl** [comment]
[Try a little profile again?](https://github.com/runtimeverification/haskell-backend/files/10108765/whoops.tar.gz)

**Comment by treeowl** [comment]
Closing for now. I don't have any great ideas for figuring out why this breaks.

**Pull request closed without merging**
