### PR TITLE
Test for functional/constructor attributes

### PR DESCRIPTION
**Pull request by u--**

### CODE REVIEW

**Comment by u--** [comment]
Jenkins: test this please

**Comment by virgil-serbanuta** [comment]
Jenkins: Test this please.

**Comment by traiansf** [comment]
Jenkins: add to whitelist

**Comment by u--** [comment]
Can virgil or traian review this please?

**Comment by grosu** [comment]
Who is @u--?  Anyway, please refer to people by their ID, so they get notified: @traiansf @virgil-serbanuta

**Pull request closed without merging**
