### PR TITLE
Create a pull request template

### PR DESCRIPTION
**Pull request by ttuegel**
The pull request template has a checklist for reviewers. It will help both
contributors and reviewers remember to check for test coverage, API
documentation, and conformance to the style guide. Although we can and should
automate some of these checks, there is no substitute for human inspection.

### CODE REVIEW

**Comment by virgil-serbanuta** [comment]
@traiansf Could you whitelist @ttuegel for running Jenkins tests?

**Comment by traiansf** [comment]
Jenkins: add to whitelist

**Comment by virgil-serbanuta** [comment]
I'm not fully sure if this is ready for review or not, but I'll assume that it is. Usually we either add a "DO NOT REVIEW" suffix to the pull request description, to mark it as incomplete, or we add someone as a reviewer.

**Comment by ttuegel** [comment]
> Usually we either add a "DO NOT REVIEW" suffix to the pull request description, to mark it as incomplete, or we add someone as a reviewer.

Yes, I intended this to be ready for review. Sorry, I wasn't sure who to add as reviewer.

**Comment by ttuegel** [comment]
@virgil-serbanuta Actually, I can't request a review because I am not a member.

**Pull request merged**
