### PR TITLE
Conservatively change import style

### PR DESCRIPTION
**Pull request by ttuegel**
---

###### Reviewer checklist

- [ ] Test coverage: `stack test --coverage`
- [ ] Public API documentation: `stack haddock`

### CODE REVIEW

**Comment by ttuegel** [comment]
I re-formatted `Kore.Repl` as an example because that has a relatively large import block.

**Comment by ttuegel** [comment]
I re-formatted `Kore.Repl` as an example because that has a relatively large import block.

**Comment by vladciobanu** [comment]
Personally, I would prefer if we stuck to one style or the other and re-format world (if we change to this new style). Other than that, I don't think I care much about which one we use.

**Comment by ttuegel** [comment]
After this hits master, every open pull request will have merge conflicts. Here's how to update your pull request smoothly:

```.sh
# Look at `git log` to find the hash of the commit immediately before
# this pull request #948 was merged to master.
git log master
# Merge the commit immediately before this one;
# replace 'BEFORE' with the hash from the last step.
git merge BEFORE
# At this point, you should fix any merge conflicts and run the tests,
# or whatever else you normally do when you merge master.
# Look at the log again and find the hash of this pull request, #948:
git log master
# Merge this commit; replace 'THIS' with the hash from the last step.
# The '-X ours' option makes git resolve all merges automatically 
# in favor of the contents of your current branch.
git merge -X ours THIS
# This may have undone some formatting, but everything should work:
stack test --pedantic
# If anything is broken, fix it and commit. Then re-apply formatting:
./scripts/stylish.sh
# and if there are any changes, commit them.
```

**Pull request merged**
