### PR TITLE
Added formal definitions, counter-examples, Grigore's answers.

### PR DESCRIPTION
**Pull request by dlucanu**
###### Reviewer checklist

- [ ] Test coverage: `stack test --coverage`
- [ ] Public API documentation: `stack haddock`
- [ ] Style conformance: `stylish-haskell`

---

### CODE REVIEW

**Comment by grosu** [comment]
@dlucanu thanks again!  I just noticed that you put me as an author of this draft.  Let's keep it without an author.  We are all working on this equally.  If/when the time comes to publish it, we will discuss the author configuration then.

**Comment by bmmoore** [comment]
jenkins: ok to test

**Comment by dlucanu** [comment]
@grosu I forgot to say that I worked on the Brandon's version of the draft, he uploaded it on github and included my comments. Therefore it is a bit different from that I send it on Slack. A part of typos and remarks regarding the syntax you mentioned were already solved by Brandon.

**Comment by dlucanu** [comment]
I added two questions regarding monotonicity and regularity, and a counter-example for the aggressive axiom.

**Comment by traiansf** [comment]
Jenkins: ok to test

**Comment by traiansf** [comment]
@dlucanu @grosu @bmmoore is this ready to be merged?

**Comment by ehildenb** [comment]
Closing as outdated, feel free to re-open and update to newest `master` if it should be merged.

**Pull request closed without merging**
