### PR TITLE
Extended + Implicit Conversions

### PR DESCRIPTION
**Pull request by msaxena2**

### CODE REVIEW

**Comment by grosu** [comment]
So this PR did not pass the tests, it seems.  Can you make it pass, so we can review it, @msaxena2 ?

**Comment by msaxena2** [comment]
[Extended KORE PR review + merge](https://trello.com/c/x8UcWz2G/12-extended-kore-pr-review-merge)

**Comment by msaxena2** [comment]
[Make Skala Backend (Kale) work With Kore + K](https://trello.com/c/fz7VSAN2/11-make-skala-backend-kale-work-with-kore-k)

**Comment by msaxena2** [comment]
[Skala Backend (Kale) on K](https://trello.com/c/IsmfWMg2/23-skala-backend-kale-on-k)

**Comment by msaxena2** [comment]
[Skala Backend (Kale) on K](https://trello.com/c/IsmfWMg2/23-skala-backend-kale-on-k)

**Comment by msaxena2** [comment]
[Skala Backend (Kale) on K](https://trello.com/c/IsmfWMg2/23-skala-backend-kale-on-k)

**Pull request closed without merging**
